export enum SignupStage {
  CREATED = 'CREATED',
  NASP_FAILED = 'NASP_FAILED',
  NOT_ELIGIBLE = 'NOT_ELIGIBLE',
  VERIFICATION_FAILED = 'VERIFICATION_FAILED',
  FAILED_FINALIZATION = 'FAILED_FINALIZATION',

  OTP_SENT = 'OTP_SENT',
  MOBILE_VERIFIED = 'MOBILE_VERIFIED',
  PERSONAL_INFO_VERIFIED = 'PERSONAL_INFO_VERIFIED',
  AGREEMENTS_ACCEPTED = 'AGREEMENTS_ACCEPTED',
  FACE_VERIFICATION_IN_PROGRESS = 'FACE_VERIFICATION_IN_PROGRESS',
  VERIFICATION_COMPLETED = 'VERIFICATION_COMPLETED',
  COMPLETED = 'COMPLETED',
}

export class SignupStageMetric {
  constructor(
    public stage: SignupStage,
    public signupRequestsNumber: number
  ) {}
}
