include:
  - project: 'oxinus-io/social-wallet-uzb/devops/ci'
    ref: "staging"
    file: '/workflows/baraka-webapp/workflow.yml'
    rules:
      - if: $CI_COMMIT_REF_NAME =~ /^staging$/
      - if: $CI_COMMIT_REF_NAME =~ /^.*\/staging\/.*$/
  - project: 'oxinus-io/social-wallet-uzb/devops/ci'
    ref: "master"
    file: '/workflows/baraka-webapp/workflow.yml'
    rules:
      - if: $CI_COMMIT_REF_NAME =~ /^production$/
      - if: $CI_COMMIT_REF_NAME =~ /.*\/release\/.*$/
  - project: 'oxinus-io/social-wallet-uzb/devops/ci'
    ref: "test"
    file: '/workflows/baraka-webapp/workflow.yml'
    rules:
      - if: $CI_COMMIT_REF_NAME =~ /.*citest.*$/
  - project: 'oxinus-io/social-wallet-uzb/devops/ci'
    ref: "development"
    file: '/workflows/baraka-webapp/workflow.yml'
    rules:
      - if: $CI_COMMIT_REF_NAME =~ /.*citest.*$/
        when: never
      - if: $CI_COMMIT_REF_NAME =~ /^production$/        
        when: never      
      - if: $CI_COMMIT_REF_NAME =~ /.*\/release\/.*$/
        when: never
      - if: $CI_COMMIT_REF_NAME =~ /^staging$/
        when: never
      - if: $CI_COMMIT_REF_NAME =~ /^.*\/staging\/.*$/
        when: never
      - if: $CI_COMMIT_REF_NAME =~ /^master$/
        when: never
      - if: $CI_COMMIT_REF_NAME =~ /^main$/
        when: never        
      - when: always

placeholder:
  only: []
  script: echo placholder