ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-slim AS builder

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_REDIRECT_URI
ARG NEXT_PUBLIC_KEYCLOAK_URL
ARG NEXT_PUBLIC_USER_TYPE

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_REDIRECT_URI=$NEXT_PUBLIC_REDIRECT_URI
ENV NEXT_PUBLIC_KEYCLOAK_URL=$NEXT_PUBLIC_KEYCLOAK_URL
ENV NEXT_PUBLIC_USER_TYPE=$NEXT_PUBLIC_USER_TYPE

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

WORKDIR /app

RUN corepack enable

COPY . /app/

RUN env

RUN yarn install --immutable

RUN yarn build

EXPOSE 3000

ENV PORT 3000

CMD ["corepack", "yarn", "run","start"]
