export class SignupRequestDetail {
  constructor(
    public id: string,
    public status: string,
    public registrationNumber: string,
    public deviceId: string,
    public firstName: string,
    public lastName: string,
    public email: string | null,
    public pinfl: string,
    public documentTypeId: string,
    public documentNumber: string,
    public dateOfBirth: string,
    public phoneCode: string,
    public phoneNumber: string,
    public phoneVerified: boolean,
    public tosAccepted: boolean,
    public tosText: string | null,
    public myIdFaceVerified: boolean,
    public privacyPolicyAccepted: boolean,
    public createdAt: string,
    public finalizedAt: string | null,
    public createdBy: string | null,
    public nationalityName: string | null,
    public citizenshipName: string | null,
    public documentType: string | null,
    public docSeria: string | null,
    public docIssueOn: string | null,
    public docExpireOn: string | null,
    public docIssueOrganization: string | null,
    public genderName: string | null,
    public birthCountryName: string | null,
    public address: string | null
  ) {}
}
